require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConnectionCategoryClassesController do

  # This should return the minimal set of attributes required to create a valid
  # ConnectionCategoryClass. As you add validations to ConnectionCategoryClass, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "code" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConnectionCategoryClassesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all connection_category_classes as @connection_category_classes" do
      connection_category_class = ConnectionCategoryClass.create! valid_attributes
      get :index, {}, valid_session
      assigns(:connection_category_classes).should eq([connection_category_class])
    end
  end

  describe "GET show" do
    it "assigns the requested connection_category_class as @connection_category_class" do
      connection_category_class = ConnectionCategoryClass.create! valid_attributes
      get :show, {:id => connection_category_class.to_param}, valid_session
      assigns(:connection_category_class).should eq(connection_category_class)
    end
  end

  describe "GET new" do
    it "assigns a new connection_category_class as @connection_category_class" do
      get :new, {}, valid_session
      assigns(:connection_category_class).should be_a_new(ConnectionCategoryClass)
    end
  end

  describe "GET edit" do
    it "assigns the requested connection_category_class as @connection_category_class" do
      connection_category_class = ConnectionCategoryClass.create! valid_attributes
      get :edit, {:id => connection_category_class.to_param}, valid_session
      assigns(:connection_category_class).should eq(connection_category_class)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ConnectionCategoryClass" do
        expect {
          post :create, {:connection_category_class => valid_attributes}, valid_session
        }.to change(ConnectionCategoryClass, :count).by(1)
      end

      it "assigns a newly created connection_category_class as @connection_category_class" do
        post :create, {:connection_category_class => valid_attributes}, valid_session
        assigns(:connection_category_class).should be_a(ConnectionCategoryClass)
        assigns(:connection_category_class).should be_persisted
      end

      it "redirects to the created connection_category_class" do
        post :create, {:connection_category_class => valid_attributes}, valid_session
        response.should redirect_to(ConnectionCategoryClass.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved connection_category_class as @connection_category_class" do
        # Trigger the behavior that occurs when invalid params are submitted
        ConnectionCategoryClass.any_instance.stub(:save).and_return(false)
        post :create, {:connection_category_class => { "code" => "invalid value" }}, valid_session
        assigns(:connection_category_class).should be_a_new(ConnectionCategoryClass)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ConnectionCategoryClass.any_instance.stub(:save).and_return(false)
        post :create, {:connection_category_class => { "code" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested connection_category_class" do
        connection_category_class = ConnectionCategoryClass.create! valid_attributes
        # Assuming there are no other connection_category_classes in the database, this
        # specifies that the ConnectionCategoryClass created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ConnectionCategoryClass.any_instance.should_receive(:update_attributes).with({ "code" => "MyString" })
        put :update, {:id => connection_category_class.to_param, :connection_category_class => { "code" => "MyString" }}, valid_session
      end

      it "assigns the requested connection_category_class as @connection_category_class" do
        connection_category_class = ConnectionCategoryClass.create! valid_attributes
        put :update, {:id => connection_category_class.to_param, :connection_category_class => valid_attributes}, valid_session
        assigns(:connection_category_class).should eq(connection_category_class)
      end

      it "redirects to the connection_category_class" do
        connection_category_class = ConnectionCategoryClass.create! valid_attributes
        put :update, {:id => connection_category_class.to_param, :connection_category_class => valid_attributes}, valid_session
        response.should redirect_to(connection_category_class)
      end
    end

    describe "with invalid params" do
      it "assigns the connection_category_class as @connection_category_class" do
        connection_category_class = ConnectionCategoryClass.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ConnectionCategoryClass.any_instance.stub(:save).and_return(false)
        put :update, {:id => connection_category_class.to_param, :connection_category_class => { "code" => "invalid value" }}, valid_session
        assigns(:connection_category_class).should eq(connection_category_class)
      end

      it "re-renders the 'edit' template" do
        connection_category_class = ConnectionCategoryClass.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ConnectionCategoryClass.any_instance.stub(:save).and_return(false)
        put :update, {:id => connection_category_class.to_param, :connection_category_class => { "code" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested connection_category_class" do
      connection_category_class = ConnectionCategoryClass.create! valid_attributes
      expect {
        delete :destroy, {:id => connection_category_class.to_param}, valid_session
      }.to change(ConnectionCategoryClass, :count).by(-1)
    end

    it "redirects to the connection_category_classes list" do
      connection_category_class = ConnectionCategoryClass.create! valid_attributes
      delete :destroy, {:id => connection_category_class.to_param}, valid_session
      response.should redirect_to(connection_category_classes_url)
    end
  end

end
