require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SalesUnitPriceByCustomersController do

  # This should return the minimal set of attributes required to create a valid
  # SalesUnitPriceByCustomer. As you add validations to SalesUnitPriceByCustomer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "product_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SalesUnitPriceByCustomersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sales_unit_price_by_customers as @sales_unit_price_by_customers" do
      sales_unit_price_by_customer = SalesUnitPriceByCustomer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sales_unit_price_by_customers).should eq([sales_unit_price_by_customer])
    end
  end

  describe "GET show" do
    it "assigns the requested sales_unit_price_by_customer as @sales_unit_price_by_customer" do
      sales_unit_price_by_customer = SalesUnitPriceByCustomer.create! valid_attributes
      get :show, {:id => sales_unit_price_by_customer.to_param}, valid_session
      assigns(:sales_unit_price_by_customer).should eq(sales_unit_price_by_customer)
    end
  end

  describe "GET new" do
    it "assigns a new sales_unit_price_by_customer as @sales_unit_price_by_customer" do
      get :new, {}, valid_session
      assigns(:sales_unit_price_by_customer).should be_a_new(SalesUnitPriceByCustomer)
    end
  end

  describe "GET edit" do
    it "assigns the requested sales_unit_price_by_customer as @sales_unit_price_by_customer" do
      sales_unit_price_by_customer = SalesUnitPriceByCustomer.create! valid_attributes
      get :edit, {:id => sales_unit_price_by_customer.to_param}, valid_session
      assigns(:sales_unit_price_by_customer).should eq(sales_unit_price_by_customer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SalesUnitPriceByCustomer" do
        expect {
          post :create, {:sales_unit_price_by_customer => valid_attributes}, valid_session
        }.to change(SalesUnitPriceByCustomer, :count).by(1)
      end

      it "assigns a newly created sales_unit_price_by_customer as @sales_unit_price_by_customer" do
        post :create, {:sales_unit_price_by_customer => valid_attributes}, valid_session
        assigns(:sales_unit_price_by_customer).should be_a(SalesUnitPriceByCustomer)
        assigns(:sales_unit_price_by_customer).should be_persisted
      end

      it "redirects to the created sales_unit_price_by_customer" do
        post :create, {:sales_unit_price_by_customer => valid_attributes}, valid_session
        response.should redirect_to(SalesUnitPriceByCustomer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sales_unit_price_by_customer as @sales_unit_price_by_customer" do
        # Trigger the behavior that occurs when invalid params are submitted
        SalesUnitPriceByCustomer.any_instance.stub(:save).and_return(false)
        post :create, {:sales_unit_price_by_customer => { "product_id" => "invalid value" }}, valid_session
        assigns(:sales_unit_price_by_customer).should be_a_new(SalesUnitPriceByCustomer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SalesUnitPriceByCustomer.any_instance.stub(:save).and_return(false)
        post :create, {:sales_unit_price_by_customer => { "product_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sales_unit_price_by_customer" do
        sales_unit_price_by_customer = SalesUnitPriceByCustomer.create! valid_attributes
        # Assuming there are no other sales_unit_price_by_customers in the database, this
        # specifies that the SalesUnitPriceByCustomer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SalesUnitPriceByCustomer.any_instance.should_receive(:update_attributes).with({ "product_id" => "1" })
        put :update, {:id => sales_unit_price_by_customer.to_param, :sales_unit_price_by_customer => { "product_id" => "1" }}, valid_session
      end

      it "assigns the requested sales_unit_price_by_customer as @sales_unit_price_by_customer" do
        sales_unit_price_by_customer = SalesUnitPriceByCustomer.create! valid_attributes
        put :update, {:id => sales_unit_price_by_customer.to_param, :sales_unit_price_by_customer => valid_attributes}, valid_session
        assigns(:sales_unit_price_by_customer).should eq(sales_unit_price_by_customer)
      end

      it "redirects to the sales_unit_price_by_customer" do
        sales_unit_price_by_customer = SalesUnitPriceByCustomer.create! valid_attributes
        put :update, {:id => sales_unit_price_by_customer.to_param, :sales_unit_price_by_customer => valid_attributes}, valid_session
        response.should redirect_to(sales_unit_price_by_customer)
      end
    end

    describe "with invalid params" do
      it "assigns the sales_unit_price_by_customer as @sales_unit_price_by_customer" do
        sales_unit_price_by_customer = SalesUnitPriceByCustomer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SalesUnitPriceByCustomer.any_instance.stub(:save).and_return(false)
        put :update, {:id => sales_unit_price_by_customer.to_param, :sales_unit_price_by_customer => { "product_id" => "invalid value" }}, valid_session
        assigns(:sales_unit_price_by_customer).should eq(sales_unit_price_by_customer)
      end

      it "re-renders the 'edit' template" do
        sales_unit_price_by_customer = SalesUnitPriceByCustomer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SalesUnitPriceByCustomer.any_instance.stub(:save).and_return(false)
        put :update, {:id => sales_unit_price_by_customer.to_param, :sales_unit_price_by_customer => { "product_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sales_unit_price_by_customer" do
      sales_unit_price_by_customer = SalesUnitPriceByCustomer.create! valid_attributes
      expect {
        delete :destroy, {:id => sales_unit_price_by_customer.to_param}, valid_session
      }.to change(SalesUnitPriceByCustomer, :count).by(-1)
    end

    it "redirects to the sales_unit_price_by_customers list" do
      sales_unit_price_by_customer = SalesUnitPriceByCustomer.create! valid_attributes
      delete :destroy, {:id => sales_unit_price_by_customer.to_param}, valid_session
      response.should redirect_to(sales_unit_price_by_customers_url)
    end
  end

end
